### ISSUE TITLE
Published maven pacakge not compatible with JVM older than Java 14

### ISSUE THREAD

**Issue by alexjg** [zalando/beard#85]
I'm running into this issue trying to use bloop, as it's not compatible with JDK 14, but I imagine anyone trying to use something older than java 14 will encounter it.

Here's a reproduction:

```
➜  bearddebug wget https://dl.bintray.com/zalando/maven/de/zalando/beard_2.13/0.3.1/beard_2.13-0.3.1.jar
➜  bearddebug jar xf ./beard_2.13-0.3.1.jar 
➜  bearddebug javap -verbose de.zalando.beard.BeardLexer | grep major
  major version: 57
```

**Comment by danpersa** [comment]
I am able to use it with JDKs other than 14.

Can you give more details about how to reproduce the problem?
Please include the stack trace and the expected behavior.

**Comment by Ravenow** [comment]
afaik it will work only for java 13+ here is an error when you try to use it on java8 for example
<pre>java.lang.UnsupportedClassVersionError: de/zalando/beard/BeardLexer has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at de.zalando.beard.parser.BeardTemplateParser.parse(BeardTemplateParser.scala:14)
	at de.zalando.beard.renderer.CustomizableTemplateCompiler.$anonfun$compile$1(DefaultTemplateCompiler.scala:40)
</pre>

**Comment by pawelkaczor** [comment]
I think this "limitation" should be mentioned in Readme.

**Comment by usommerl** [comment]
I'm hitting the same problem when I try to use it with JDK 11:

```
java.lang.UnsupportedClassVersionError: de/zalando/beard/BeardLexer has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
  at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
  at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
  ...
```

I agree that the minimum required JDK version should be mentioned in the README because I can imagine that there are a lot of potential users that don't use JDK 13+.

P.S.: The [general recommendation on scala-lang.org](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#:~:text=We%20generally%20recommend%20JDK%208,experimental%E2%80%9D%20or%20%E2%80%9Cunsafe%E2%80%9D.) is to compile source code with JDK 8 or 11. Therefore, a lot of people will face this issue.

**Comment by leviferreira** [comment]
This repo is now unmaintained and will be archived.
